pipeline:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.110.0

- name: deploy
  image: appleboy/drone-scp:latest
  settings:
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    source: "./public/*"
    target: "/home/codeberg/hugo/gomarcd.dev"