pipeline:
  deploy:
    image: appleboy/drone-ssh:linux-amd64
    secrets:
      - ssh_host
      - ssh_username
      - ssh_key
    commands:
      - cd /home/codeberg/hugo/gomarcd.dev
      - git pull
    when:
      event: push