pipeline:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.110.0

- name: deploy
  image: appleboy/drone-ssh:linux-amd64
  settings:
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    command_timeout: 2m
    script:
      - cd /home/codeberg/hugo/gomarcd.dev && git pull